server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers
spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:./h2/user;AUTO_SERVER=TRUE # this one is on the disk, notice the h2 folder and contents it creates
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      # http://localhost:8080/api/h2-console
      enabled: true

logging.level.com.vocabulary.vocabularybackend.controller.WordController: DEBUG
